In [2]:
import pandas as pd
import requests
import zipfile
import datetime as dt
import pandas as pd
from openpyxl import load_workbook

In [3]:
hoje = dt.datetime.today().strftime('%Y%m%d')
hoje
ano = hoje[:4]
mes = hoje[4:6]
dia = hoje[6:]
ano, mes, dia

('2023', '03', '27')

In [4]:
url = f"https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_{ano}{mes}.zip"

In [5]:
#deletar todos os arquivos zip do diretório
import glob
import os
for f in glob.glob("*.zip"):
    os.remove(f)

In [6]:
download = requests.get(url)

with open(f"inf_diario_fi_{ano}{mes}.zip", "wb") as arquivo_cvm:
    arquivo_cvm.write(download.content)

arquivo_zip = zipfile.ZipFile(f"inf_diario_fi_{ano}{mes}.zip")

In [7]:
dados_fundos = pd.read_csv(arquivo_zip.open(arquivo_zip.namelist()[0]), sep=";", encoding="ISO-8859-1", dtype= str)

dados_fundos

,TP_FUNDO,CNPJ_FUNDO,DT_COMPTC,VL_TOTAL,VL_QUOTA,VL_PATRIM_LIQ,CAPTC_DIA,RESG_DIA,NR_COTST
0,FI,00.017.024/0001-53,2023-03-01,1072505.85,31.510600300000,1074201.96,0.00,0.00,1
1,FI,00.017.024/0001-53,2023-03-02,1073063.54,31.526931100000,1074758.68,0.00,0.00,1
2,FI,00.017.024/0001-53,2023-03-03,1070886.05,31.541703100000,1072317.28,0.00,2944.98,1
3,FI,00.017.024/0001-53,2023-03-06,1071192.98,31.555778600000,1072795.80,0.00,0.00,1
4,FI,00.017.024/0001-53,2023-03-07,1071467.47,31.570082300000,1073282.08,0.00,0.00,1
...,...,...,...,...,...,...,...,...,...
418778,FI,97.929.213/0001-34,2023-03-17,75755594.34,10.005343810000,76033822.59,0.00,0.00,2
418779,FI,97.929.213/0001-34,2023-03-20,77966178.67,10.296173130000,78243928.07,0.00,0.00,2
418780,FI,97.929.213/0001-34,2023-03-21,78398389.88,10.352983680000,78675649.67,0.00,0.00,2
418781,FI,97.929.213/0001-34,2023-03-22,78979505.57,10.429388390000,79256273.64,0.00,0.00,2
418782,FI,97.929.213/0001-34,2023-03-23,78983243.02,10.429815130000,79259516.54,0.00,0.00,2

In [8]:
dados_cadastro = pd.read_csv('https://dados.cvm.gov.br/dados/FI/CAD/DADOS/cad_fi.csv', sep=";", encoding="ISO-8859-1")

dados_cadastro = dados_cadastro[['CNPJ_FUNDO', 'DENOM_SOCIAL']]
dados_cadastro = dados_cadastro.drop_duplicates()
dados_cadastro

C:\Users\ricar\AppData\Local\Temp\ipykernel_17396\1312422791.py:1: DtypeWarning: Columns (14,17,18,20,22,24,27,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  dados_cadastro = pd.read_csv('https://dados.cvm.gov.br/dados/FI/CAD/DADOS/cad_fi.csv', sep=";", encoding="ISO-8859-1")

               CNPJ_FUNDO                                       DENOM_SOCIAL
0      00.000.684/0001-21  DEUTSCHE BANK FDO APLIC QUOTAS FDO INV FINANCE...
1      00.000.731/0001-37  ITAMARITI CASH FUNDO APLICACAO QUOTAS FDOS INV...
2      00.000.732/0001-81  FUNDO APLIC. QUOTAS DE F.I. SANTANDER CURTO PRAZO
3      00.000.740/0001-28  FUNDO DE APLIC EM QUOTAS DE FUNDOS DE INV BMC ...
4      00.000.749/0001-39  BALANCE FUNDO APLICACAO QUOTAS FUNDO INVESTIME...
...                   ...                                                ...
71648  28.850.140/0001-78  FUNDO DE FINANCIAMENTO DA INDUSTRIA CINEMATOGR...
71649  28.912.043/0001-62  HAPVIDA - FUNDO DE FINANCIAMENTO DA INDUSTRIA ...
71650  31.674.280/0001-47  MEDIA VENTURE ESG INCENTIVADO - FUNDO DE FINAN...
71651  32.222.962/0001-81  Fundo de Financiamento da Indústria Cinematogr...
71652  48.879.897/0001-00  FUNDO DE  FINANCIAMENTO DA INDÚSTRIA CINEMATOG...

[63057 rows x 2 columns]

In [9]:
base_final = pd.merge(dados_fundos, dados_cadastro, how='left', left_on='CNPJ_FUNDO', right_on='CNPJ_FUNDO')

base_final = base_final[['DT_COMPTC', 'CNPJ_FUNDO', 'DENOM_SOCIAL', 'VL_QUOTA', 'VL_PATRIM_LIQ']]
base_final

,DT_COMPTC,CNPJ_FUNDO,DENOM_SOCIAL,VL_QUOTA,VL_PATRIM_LIQ
0,2023-03-01,00.017.024/0001-53,FUNDO DE INVESTIMENTO RENDA FIXA EXPONENCIAL,31.510600300000,1074201.96
1,2023-03-02,00.017.024/0001-53,FUNDO DE INVESTIMENTO RENDA FIXA EXPONENCIAL,31.526931100000,1074758.68
2,2023-03-03,00.017.024/0001-53,FUNDO DE INVESTIMENTO RENDA FIXA EXPONENCIAL,31.541703100000,1072317.28
3,2023-03-06,00.017.024/0001-53,FUNDO DE INVESTIMENTO RENDA FIXA EXPONENCIAL,31.555778600000,1072795.80
4,2023-03-07,00.017.024/0001-53,FUNDO DE INVESTIMENTO RENDA FIXA EXPONENCIAL,31.570082300000,1073282.08
...,...,...,...,...,...
418812,2023-03-17,97.929.213/0001-34,WHG SISTEMA II FUNDO DE INVESTIMENTO MULTIMERC...,10.005343810000,76033822.59
418813,2023-03-20,97.929.213/0001-34,WHG SISTEMA II FUNDO DE INVESTIMENTO MULTIMERC...,10.296173130000,78243928.07
418814,2023-03-21,97.929.213/0001-34,WHG SISTEMA II FUNDO DE INVESTIMENTO MULTIMERC...,10.352983680000,78675649.67
418815,2023-03-22,97.929.213/0001-34,WHG SISTEMA II FUNDO DE INVESTIMENTO MULTIMERC...,10.429388390000,79256273.64
418816,2023-03-23,97.929.213/0001-34,WHG SISTEMA II FUNDO DE INVESTIMENTO MULTIMERC...,10.429815130000,79259516.54

In [10]:
def atualizar_cnpjs(novos_cnpjs):
    global lista_cnpjs
    lista_cnpjs = novos_cnpjs

In [14]:
atualizar_cnpjs(['43.677.242/0001-27',
 '32.302.284/0001-67',
 '20.852.239/0001-05',
 '13.950.115/0001-99'])

In [17]:
lista_cnpjs

['43.677.242/0001-27',
 '32.302.284/0001-67',
 '20.852.239/0001-05',
 '13.950.115/0001-99']

In [ ]:
dia = int(hoje[6:]) - 10
#filtrar para achar o o VL_QUOTA dos CNPJS no dia de hoje menos 2
base_filtro = base_final[base_final['CNPJ_FUNDO'].isin(lista_cnpjs)] #filtrar para achar o o VL_QUOTA dos CNPJS no dia de hoje menos 2
base_filtro = base_filtro[base_filtro['DT_COMPTC'] == f"{ano}-{mes}-{dia}"] #filtrar para achar o o VL_QUOTA dos CNPJS no dia de hoje menos 2
#Mostrar apenas os campos CNPJ_FUNDO, DENOM_SOCIAL, VL_QUOTA
base_filtro = base_filtro[['DT_COMPTC','CNPJ_FUNDO', 'DENOM_SOCIAL', 'VL_QUOTA']]
#coverter o campo VL_QUOTA para numero sem diminuir a precisão
#converter ponto para virgula na coluna VL_QUOTA
base_filtro['VL_QUOTA'] = base_filtro['VL_QUOTA'].str.replace('.', ',')
base_filtro

In [ ]:
#salvar num arquivo excel na aba do dia
nome_da_aba = f"{dia}_{mes}_{ano}"
nome_arquivo = "Fundos_CVM.xlsx"
book = load_workbook(nome_arquivo)
if nome_da_aba in book.sheetnames:
    # se a aba já existe, sobrescreve os dados
    writer = pd.ExcelWriter(nome_arquivo, engine='openpyxl')
    writer.book = book
    writer.sheets = dict((ws.title, ws) for ws in book.worksheets)
    base_filtro.to_excel(writer, sheet_name=nome_da_aba, index=False)
    writer.save()
else:
    # se a aba não existe, cria uma nova aba
    with pd.ExcelWriter(nome_arquivo, engine='openpyxl') as writer:
        writer.book = book
        base_filtro.to_excel(writer, sheet_name=nome_da_aba, index=False)
        writer.save()